{
 "title": "pgnotify-rabbitmq",
 "description": "Nodejs runtime metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(nodejs_active_handles, group)"
    }
   },
   {
    "name": "stack",
    "label": "Stack",
    "query": {
     "query": "label_values(nodejs_active_handles{group=\"$group\"},stack)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(nodejs_active_handles,service)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nodejs_active_handles{stack=\"$stack\",service=\"$service\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Messages (runtime)",
   "type": "stat",
   "description": "Número total de mensajes y ack's procesados por channel de notify desde el último inicio del app",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "pgnotify_rabbitmq_messages{}", "legendFormat": "{{notify}} {{space}}" }
   ]
  },
  {
   "title": "Messages per minutes (runtime)",
   "type": "timeseries",
   "description": "Mensajes y ack's por segundos según channel de notify",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pgnotify_rabbitmq_ack{}[$__interval])",
     "legendFormat": "{{notify}} {{space}} (Messages)"
    }
   ]
  },
  {
   "title": "$service Process Heap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 9 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_process_heap_bytes{}"
    }
   ]
  },
  {
   "title": "$service Metrics scrape duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 9 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"notify_rabbitmq:9021\"}"
    }
   ]
  },
  {
   "title": "$service Max file descriptors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_process_max_fds{}"
    }
   ]
  },
  {
   "title": "$service Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_process_open_fds{}"
    }
   ]
  },
  {
   "title": "$service Nodejs Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_nodejs_version_info{}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$service Process start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 10 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pgnotify_rabbitmq_process_start_time_seconds{service=~\"$service\", stack=~\"$stack\"})*1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_nodejs_active_handles{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} {{type}}"
    },
    {
     "expr": "pgnotify_rabbitmq_nodejs_active_handles_total  {service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} Total"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_nodejs_eventloop_lag_seconds{}",
     "legendFormat": "{{service}} Event Loop Lag"
    }
   ]
  },
  {
   "title": "% CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(pgnotify_rabbitmq_process_cpu_user_seconds_total{service=~\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} User"
    },
    {
     "expr": "rate(pgnotify_rabbitmq_process_cpu_system_seconds_total{service=~\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} System"
    },
    {
     "expr": "rate(pgnotify_rabbitmq_process_cpu_seconds_total{service=~\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} Total"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "External Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_nodejs_external_memory_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} External Memory"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_nodejs_heap_size_total_bytes{}",
     "legendFormat": "{{service}} Total"
    },
    {
     "expr": "pgnotify_rabbitmq_nodejs_heap_size_used_bytes{}",
     "legendFormat": "{{service}} Used"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_process_resident_memory_bytes{}",
     "legendFormat": "{{service}} Resident"
    },
    {
     "expr": "pgnotify_rabbitmq_process_virtual_memory_bytes{}",
     "legendFormat": "{{service}} Virtual"
    }
   ]
  },
  { "title": "Heap Space Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_nodejs_heap_space_size_total_bytes{}",
     "legendFormat": "{{service}} {{space}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_nodejs_heap_space_size_available_bytes{}",
     "legendFormat": "{{service}}-{{space}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pgnotify_rabbitmq_nodejs_heap_space_size_used_bytes{}",
     "legendFormat": "{{service}} {{space}}"
    }
   ]
  }
 ]
}